Suppress ranges
jfalcou/eve pull request #1509
Opened 2022-12-31 14:47 UTC by jtlap

2023-01-02 17:06 UTC, jfalcou requested changes

2023-01-02 17:06 UTC, jfalcou commented on include/eve/module/bessel/regular/impl/cyl_bessel_j0.hpp
> +      static const A6 PC     = {2.2779090197304684302e+04,
should be constexpr ?

2023-01-02 17:06 UTC, jfalcou commented on include/eve/module/bessel/regular/impl/cyl_bessel_i1.hpp
> +        static const A8 P    = {8.333333221e-02f,
should be constexpr

2023-01-02 17:06 UTC, jfalcou commented on include/eve/module/bessel/regular/impl/cyl_bessel_i0.hpp
> +      static const A9 P = {1.00000003928615375e+00f,
should be constexpr

2023-01-02 17:06 UTC, jfalcou commented on include/eve/module/bessel/regular/impl/cyl_bessel_j1.hpp
> +    A7 PC     = {-4.4357578167941278571e+06,
should be constexpr

2023-01-02 17:06 UTC, jfalcou commented on include/eve/module/bessel/regular/impl/cyl_bessel_k0.hpp
> +        static const A3 P = {
should be constexpr

2023-01-02 17:06 UTC, jfalcou commented on include/eve/module/bessel/regular/impl/cyl_bessel_k1.hpp
> +        static const A3 P = {
should be constexpr

2023-01-02 17:06 UTC, jfalcou commented on include/eve/module/bessel/regular/impl/cyl_bessel_y0.hpp
> +    static const A6 P1 = {1.0723538782003176831e+11,
should be constexpr

2023-01-02 17:06 UTC, jfalcou commented on include/eve/module/bessel/regular/impl/cyl_bessel_y1.hpp
> +    static const A7 P1 = {4.0535726612579544093e+13,
should be constexpr

2023-01-02 17:06 UTC, jfalcou commented on include/eve/module/polynomial/detail/horner_impl.hpp
> +// template<decorator D, value T0, range R>
delete don't  comment

2023-01-02 17:06 UTC, jfalcou commented on include/eve/module/polynomial/detail/horner_impl.hpp
> +// template<value T0, range R>
delete dont comment

2023-01-02 17:06 UTC, jfalcou commented on include/eve/module/special/regular/impl/lambert.hpp
> +    A3 P = {
should be constexpr

2023-01-02 19:34 UTC, jfalcou commented on include/eve/module/bessel/regular/impl/cyl_bessel_j1.hpp
> +    A7 PC     = {-4.4357578167941278571e+06,
This one is still not constexpr

2023-01-03 09:21 UTC, jtlap commented on include/eve/module/bessel/regular/impl/cyl_bessel_j1.hpp
> +    A7 PC     = {-4.4357578167941278571e+06,
je crois que j'ai tout fait là

2023-01-03 10:03 UTC, jfalcou approved these changes

2023-01-03 10:04 UTC, merged