Bit and byte reverse
jfalcou/eve pull request #1592
Opened 2023-03-23 21:35 UTC by jtlap

2023-03-25 18:56 UTC, jfalcou reviewed
fix the doc and investigate intrinsics

2023-03-26 13:59 UTC, DenisYaroshevskiy commented
Are you sure it's not byte_swap? Is it little - big endian thing for bytes?

2023-03-28 14:51 UTC, DenisYaroshevskiy commented
Please then in the comment/ doc say byte_swap for searching ( i didn't look - maybe you already do)

2023-03-28 20:16 UTC, jfalcou requested changes

2023-03-28 20:16 UTC, jfalcou commented on test/unit/module/core/reverse.cpp
> +//   auto frx =  [&](size_t i, size_t size) { return x.get(size - i - 1); };
reemoove doOoOn't Comememement

2023-03-28 20:17 UTC, jtlap commented on test/unit/module/core/reverse.cpp
> +//   auto frx =  [&](size_t i, size_t size) { return x.get(size - i - 1); };
ok

2023-03-29 08:10 UTC, jfalcou commented
The doc says: 

```c++
//!   @note eve::byte_reverse is the functional equivalent to std::byte_swap.
//!   However, we decided to name it byte_reverse in order to keep a proper naming
//!   scheme aligned with the eve::bit_swap/eve::bit_reverse functions.
```

2023-03-30 06:44 UTC, jfalcou approved these changes

2023-03-30 14:46 UTC, jfalcou approved these changes

2023-03-30 14:46 UTC, merged