sum/dif_of_prod real and complex update
jfalcou/eve pull request #1606
Opened 2023-05-29 18:02 UTC by jtlap

2023-05-30 15:32 UTC, jfalcou commented on include/eve/module/complex/detail/arithmetic.hpp
> +    return z1*z2 + z3*z4;
no FMA ?

2023-05-30 15:36 UTC, jfalcou requested changes
-> The raw and pedantic version need test, as the diff_of_prod pedantic is wrong.

2023-05-30 15:36 UTC, jfalcou commented on include/eve/module/complex/detail/arithmetic.hpp
> +    return z1*z2 + z3*z4;
no FMA/FNMS ?

2023-05-30 15:36 UTC, jfalcou commented on include/eve/module/core/pedantic/impl/diff_of_prod.hpp
> +    return pedantic(sum_of_prod)(r_t(a), r_t(b), r_t(c), r_t(d));
shouldn't it be `diff_of_prod` ?

2023-05-30 19:59 UTC, jtlap commented on include/eve/module/complex/detail/arithmetic.hpp
> +    return z1*z2 + z3*z4;
ok fma

2023-05-30 19:59 UTC, jtlap commented on include/eve/module/core/pedantic/impl/diff_of_prod.hpp
> +    return pedantic(sum_of_prod)(r_t(a), r_t(b), r_t(c), r_t(d));
yes

2023-06-16 11:47 UTC, jfalcou approved these changes

2023-06-16 11:48 UTC, merged