New style/combinatorial
jfalcou/eve pull request #1729
Opened 2024-01-17 12:48 UTC by jtlap

The job is not fully done as conversion decorators are not still available in new style
impact is on primes family and lcm

2024-01-17 18:01 UTC, jfalcou requested changes

2024-01-17 20:03 UTC, jtlap commented on include/eve/module/combinatorial/regular/impl/lcm.hpp
> +// template<value T>
No. I leave here the conversion implementation that can not work today but commented
I hope uncomment it soon

2024-01-18 14:26 UTC, jfalcou requested changes

2024-01-18 14:26 UTC, jfalcou commented on test/doc/combinatorial/conversion.inactive/lcm.cpp
> +//TODO            << " -> upgrade_(lcm)(pi8, qi8))    = " << eve::upgrade_(eve::lcm)(pi8, qi8) << '\n'
it is done just above no ?

2024-01-18 14:28 UTC, jfalcou commented
The functions and operator() lacks constexpr like we decided beforehand

2024-01-19 10:41 UTC, jfalcou approved these changes

2024-01-19 10:42 UTC, merged