replacing old converters
jfalcou/eve pull request #1787
Opened 2024-05-01 18:56 UTC by jtlap

2024-05-02 17:14 UTC, jfalcou requested changes

2024-05-02 17:14 UTC, jfalcou commented on benchmarks/module/combinatorial/gcd/regular/gcd.hpp
> +  auto std__gcd =  [](auto x,  auto y){return std::gcd(eve::int_(x, to_int<decltype(x)), eve::convert(y, int_from<decltype(y))); };
Missing convert here

2024-05-02 17:14 UTC, jfalcou commented on include/eve/module/core/regular/converter.hpp
> +  using uint_converter = decorated<convert_by_<as_uinteger>()>;
shouldn't this file be removed now ?

2024-05-02 18:45 UTC, jtlap commented on benchmarks/module/combinatorial/gcd/regular/gcd.hpp
> +  auto std__gcd =  [](auto x,  auto y){return std::gcd(eve::int_(x, to_int<decltype(x)), eve::convert(y, int_from<decltype(y))); };
done

2024-05-02 18:45 UTC, jtlap commented on include/eve/module/core/regular/converter.hpp
> +  using uint_converter = decorated<convert_by_<as_uinteger>()>;
done

2024-05-03 14:47 UTC, jfalcou requested changes

2024-05-03 14:47 UTC, jfalcou commented on include/eve/module/core/regular/impl/next.hpp
> +      return bitfloating(bitinteger(a) + convert(as<elementype_t<i_t>>());
There is something fishy here, this code is wrong yet compiles. Cna you check the include/usefulness of this file ?

2024-05-03 14:47 UTC, jfalcou commented on include/eve/module/math/regular/exp2.hpp
> +      using i_t  = as_integer_t<element_type_t<b_t>>;
isn't it int_from then ?

2024-05-03 14:47 UTC, jfalcou commented on test/unit/module/core/convert/to_tuple.cpp
> -//==================================================================================================
this file should still be there

2024-05-05 17:47 UTC, jtlap commented on test/unit/module/core/convert/to_tuple.cpp
> -//==================================================================================================
done

2024-05-05 18:12 UTC, jtlap commented on include/eve/module/math/regular/exp2.hpp
> +      using i_t  = as_integer_t<element_type_t<b_t>>;
don't think so as b_t can be unsigned

2024-05-06 18:36 UTC, jfalcou approved these changes

2024-05-06 18:38 UTC, jfalcou approved these changes

2024-05-06 18:38 UTC, merged