trunc correction and augmented tests
jfalcou/eve pull request #1807
Opened 2024-05-19 15:04 UTC by jtlap

the fuzzy version was not correct
also tests are added

2024-05-19 15:09 UTC, jfalcou requested changes

2024-05-19 15:09 UTC, jfalcou commented on include/eve/module/core/regular/impl/trunc.hpp
> +#include <iostream>
remove

2024-05-19 16:48 UTC, jtlap commented on include/eve/module/core/regular/impl/trunc.hpp
> +#include <iostream>
done

2024-05-20 07:36 UTC, jfalcou approved these changes

2024-05-20 07:37 UTC, merged