Fix ror & mask_ror x86 backend
jfalcou/eve pull request #1826
Opened 2024-05-28 20:11 UTC by SadiinsoSnowfall

Fixing ror & mask_ror impl in eve
first commit should not pass CI by design

2024-05-29 12:54 UTC, jtlap commented
perhaps you can add doc based on shl file pattern

2024-05-29 17:08 UTC, jfalcou requested changes

2024-05-29 17:08 UTC, jfalcou commented on include/eve/module/core/regular/impl/rotl.hpp
> +  template<unsigned_value T, typename S, callable_options O>
this normally useless as the cocnept checkign is done on operator()

2024-05-29 17:08 UTC, jfalcou commented on include/eve/module/core/regular/impl/rotl.hpp
> +  template<unsigned_value T, auto S, callable_options O>
this normally useless as the cocnept checkign is done on operator()

2024-05-29 17:08 UTC, jfalcou commented on include/eve/module/core/regular/rotl.hpp
> +  //!      The call `rotl(x, n)` is equivalent to `std::rotl(x, n)` if `x` is an [simd value](@ref
sounds weird

2024-05-29 17:08 UTC, jfalcou commented on include/eve/module/core/regular/rotr.hpp
> +  //!      The call `rotr(x, n)` is equivalent to `std::rotr(x, n)` if `x` is an [simd value](@ref
same. we probably means to say : on scalar value OR to say it is done on each lanes.

2024-05-29 20:48 UTC, jtlap approved these changes

2024-05-30 17:16 UTC, jfalcou approved these changes

2024-05-30 17:17 UTC, merged