Div
jfalcou/eve pull request #1843
Opened 2024-06-07 13:09 UTC by jtlap

2024-06-09 11:44 UTC, jfalcou requested changes
- Did you forget to remove the div and rem from operators.hpp ?
- I thought we wanted fmod to be rem for float and rem not supporting float anymore ?

2024-06-09 11:44 UTC, jfalcou commented on include/eve/module/core/regular/div.hpp
> +//! @divtogroup core_arithmetic
@addtogroup

2024-06-09 11:49 UTC, jfalcou commented on include/eve/module/core/regular/rem.hpp
> +// #if defined(EVE_INCLUDE_ARM_HEADER)
Remove or uncomment ?

2024-06-09 11:50 UTC, jfalcou commented on include/eve/module/core/regular/fmod.hpp
> +//!      eve::common_value_t<T, U> rem(T x, U y) noexcept;
rem is fmod here

2024-06-09 12:07 UTC, jtlap commented on include/eve/module/core/regular/div.hpp
> +//! @divtogroup core_arithmetic
lol done

2024-06-09 12:08 UTC, jtlap commented on include/eve/module/core/regular/rem.hpp
> +// #if defined(EVE_INCLUDE_ARM_HEADER)
removed

2024-06-09 12:10 UTC, jtlap commented on include/eve/module/core/regular/fmod.hpp
> +//!      eve::common_value_t<T, U> rem(T x, U y) noexcept;
done and put floating_value as doc says

2024-06-10 07:43 UTC, jfalcou commented on include/eve/module/core/regular/rem.hpp
> -#  include <eve/module/core/regular/impl/simd/arm/neon/rem.hpp>
maybe we can remove the file then

2024-06-10 19:07 UTC, merged