Doc v2 l
jfalcou/eve pull request #1876
Opened 2024-07-03 11:25 UTC by jtlap

2024-07-03 19:59 UTC, jfalcou requested changes

2024-07-03 19:59 UTC, jfalcou commented on include/eve/module/combinatorial/regular/lcm.hpp
>  //!    Returns the least common multiple of |p| and |n|.
where are 1. and 2. ???

2024-07-03 19:59 UTC, jfalcou commented on include/eve/module/core/regular/ldexp.hpp
> +//!     3. Takes extra care to handling limit values.
what about listing them ?

2024-07-03 19:59 UTC, jfalcou commented on include/eve/module/core/regular/lerp.hpp
> +//!      2. `pedantic` version of fma is used internally.
Where is 3.

2024-07-04 07:34 UTC, jtlap commented on include/eve/module/combinatorial/regular/lcm.hpp
>  //!    Returns the least common multiple of |p| and |n|.
done

2024-07-04 07:38 UTC, jtlap commented on include/eve/module/core/regular/ldexp.hpp
> +//!     3. Takes extra care to handling limit values.
done

2024-07-04 07:40 UTC, jtlap commented on include/eve/module/core/regular/lerp.hpp
> +//!      2. `pedantic` version of fma is used internally.
done

2024-07-06 08:23 UTC, jfalcou approved these changes

2024-07-06 13:17 UTC, merged