Doc v2 n
jfalcou/eve pull request #1878
Opened 2024-07-06 08:06 UTC by jtlap

2024-07-06 20:15 UTC, jfalcou requested changes

2024-07-06 20:15 UTC, jfalcou commented on include/eve/module/math/regular/newton.hpp
> +//!      constexpr auto horner(value auto x, value auto ... cmi)                       noexcept; // 1
copy pasted error

2024-07-07 07:35 UTC, jtlap commented on include/eve/module/math/regular/newton.hpp
> +//!      constexpr auto horner(value auto x, value auto ... cmi)                       noexcept; // 1
done

2024-07-07 13:15 UTC, jfalcou approved these changes

2024-07-07 13:15 UTC, merged