ps
jfalcou/eve pull request #1879
Opened 2024-07-06 20:10 UTC by jtlap

2024-07-06 20:19 UTC, jfalcou requested changes

2024-07-06 20:19 UTC, jfalcou commented on include/eve/module/math/regular/pow.hpp
> +//!     3. speedier must less accurate call
Faster is the correct word

2024-07-06 20:19 UTC, jfalcou commented on include/eve/module/math/regular/pow1p.hpp
> +//!     3. speedier must less accurate call.
Faster

2024-07-06 20:19 UTC, jfalcou commented on include/eve/module/math/regular/pow_abs.hpp
> +//!     3. speedier must less accurate call.
Faster

2024-07-06 20:19 UTC, jfalcou commented on include/eve/module/math/regular/powm1.hpp
> +//!     3. speedier must less accurate call.
Faster

2024-07-07 07:39 UTC, jtlap commented on include/eve/module/math/regular/pow.hpp
> +//!     3. speedier must less accurate call
done

2024-07-07 07:39 UTC, jtlap commented on include/eve/module/math/regular/pow1p.hpp
> +//!     3. speedier must less accurate call.
done

2024-07-07 07:39 UTC, jtlap commented on include/eve/module/math/regular/pow_abs.hpp
> +//!     3. speedier must less accurate call.
done

2024-07-07 07:39 UTC, jtlap commented on include/eve/module/math/regular/powm1.hpp
> +//!     3. speedier must less accurate call.
done

2024-07-08 06:04 UTC, jfalcou approved these changes

2024-07-08 06:05 UTC, merged