New combinatorial.cpp
jfalcou/eve pull request #1902
Opened 2024-07-21 16:46 UTC by jtlap

2024-07-22 12:57 UTC, SATYAPAL-BISHNOI commented
,

2024-07-23 10:09 UTC, jfalcou requested changes

2024-07-23 10:09 UTC, jfalcou commented on test/doc/CMakeLists.txt
> +##glob_unit("doc" ${doc_root} "combinatorial/conversion/*.cpp" )
remove donc comment

2024-07-23 10:09 UTC, jfalcou commented on test/unit/module/combinatorial/fibonacci.cpp
> -TTS_CASE_TPL("Check corner-cases behavior of eve::fibonacci on wide", eve::test::simd::ieee_reals)
put it back maybe ?

2024-07-23 10:22 UTC, jtlap commented on test/doc/CMakeLists.txt
> +##glob_unit("doc" ${doc_root} "combinatorial/conversion/*.cpp" )
done

2024-07-23 10:22 UTC, jtlap commented on test/unit/module/combinatorial/fibonacci.cpp
> -TTS_CASE_TPL("Check corner-cases behavior of eve::fibonacci on wide", eve::test::simd::ieee_reals)
done

2024-07-23 11:11 UTC, jfalcou approved these changes

2024-07-25 13:23 UTC, merged