A trigo pb
jfalcou/eve pull request #1908
Opened 2024-07-31 15:13 UTC by jtlap

a bug on rem180 and suppressing some uneedded options for direct trigo in degrees and pis

2024-07-31 15:34 UTC, jfalcou requested changes
Lot of bad placemetn of //====

2024-07-31 15:34 UTC, jfalcou commented on include/eve/module/math/regular/acotd.hpp
> +//================================================================================================
double comments

2024-07-31 15:34 UTC, jfalcou commented on include/eve/module/math/regular/acsc.hpp
> +//================================================================================================
why not the same length of === ?

2024-07-31 15:34 UTC, jfalcou commented on include/eve/module/math/regular/acscd.hpp
> +//================================================================================================
why not the same length of === ?

2024-07-31 15:34 UTC, jfalcou commented on include/eve/module/math/regular/agd.hpp
> +//================================================================================================
why not the same length of === ?

2024-07-31 15:34 UTC, jfalcou commented on include/eve/module/math/regular/asec.hpp
> +  inline constexpr auto asec = functor<asec_t>;
why not the same length of === ?

2024-07-31 15:34 UTC, jfalcou commented on include/eve/module/math/regular/asecd.hpp
> +//================================================================================================
Double =====

2024-07-31 15:34 UTC, jfalcou commented on include/eve/module/math/regular/asech.hpp
> +  inline constexpr auto asech = functor<asech_t>;
why not the same length of === ?

2024-07-31 15:34 UTC, jfalcou commented on include/eve/module/math/regular/asin.hpp
> +//================================================================================================
why not the same length of === ?

2024-07-31 15:34 UTC, jfalcou commented on include/eve/module/math/regular/atan.hpp
> + inline constexpr auto atan = functor<atan_t>;
why not the same length of === ?

2024-07-31 15:34 UTC, jfalcou commented on include/eve/module/math/regular/atand.hpp
> +//================================================================================================
double //===========

2024-07-31 15:34 UTC, jfalcou commented on include/eve/module/math/regular/atanh.hpp
> +  inline constexpr auto atanh = functor<atanh_t>;
why not the same length of === ?

2024-07-31 15:34 UTC, jfalcou commented on include/eve/module/math/regular/cbrt.hpp
> +  inline constexpr auto cbrt = functor<cbrt_t>;
double //===============

2024-07-31 15:34 UTC, jfalcou commented on include/eve/module/math/regular/cospi.hpp
> +  struct cospi_t : elementwise_callable<cospi_t, Options, quarter_circle_option>
cosd accepts big_option. Why not this one ? or is it an error on cosd ?

2024-07-31 15:34 UTC, jfalcou commented on include/eve/module/math/regular/cospi.hpp
> +//================================================================================================
Double //==

2024-07-31 15:34 UTC, jfalcou commented on include/eve/module/math/regular/tanpi.hpp
> +//================================================================================================
double //===============

2024-07-31 15:34 UTC, jfalcou commented on include/eve/module/math/regular/tand.hpp
> +//================================================================================================
DOuble //===========

2024-07-31 18:33 UTC, jtlap commented on include/eve/module/math/regular/tand.hpp
> +//================================================================================================
all done

2024-07-31 18:33 UTC, jtlap commented
J'ai tout passé en revue et corrigé

2024-08-01 07:18 UTC, jfalcou requested changes

2024-08-01 07:18 UTC, jfalcou commented on include/eve/module/math/regular/rem_pio2.hpp
> -//==================================================================================================
To delete ???

2024-08-01 11:26 UTC, jtlap commented on include/eve/module/math/regular/rem_pio2.hpp
> -//==================================================================================================
non je l'ai rétabli. just merge

2024-08-01 13:18 UTC, jfalcou approved these changes

2024-08-01 13:18 UTC, merged