Adding sigmoid and chi
jfalcou/eve pull request #1911
Opened 2024-08-05 15:57 UTC by jtlap

2024-08-05 16:14 UTC, jtlap commented
abel also was added in polynomial

2024-08-05 16:23 UTC, jfalcou requested changes

2024-08-05 16:23 UTC, jfalcou commented on include/eve/module/core/regular/chi.hpp
> +//!   @brief `elementwise_callable` indicatrix of the interval \f$[lo, hi[\f$ or of the set for which the invocable returns true.
it is not elementwise

2024-08-05 20:31 UTC, jtlap commented on include/eve/module/core/regular/chi.hpp
> +//!   @brief `elementwise_callable` indicatrix of the interval \f$[lo, hi[\f$ or of the set for which the invocable returns true.
done

2024-08-06 07:13 UTC, jfalcou approved these changes

2024-08-06 07:14 UTC, merged