Oriented arithmetic b
jfalcou/eve pull request #1974
Opened 2024-09-22 08:20 UTC by jtlap

inc dec fma rec sqrt oneminus can be oriented

2024-09-23 11:49 UTC, jfalcou requested changes

2024-09-23 12:04 UTC, jtlap commented on include/eve/module/core/detail/roundings.hpp
> +// #if __GNUC__ >= 13
done

2024-09-23 12:04 UTC, jtlap commented on include/eve/module/core/detail/roundings.hpp
> -
done

2024-09-23 12:06 UTC, jtlap commented on include/eve/module/core/regular/fast_two_add.hpp
> +//================================================================================================
j'y ai pensé mais c'est pas vraiment ça il faudrait un decorator +specifique genre limited. C'est le nom classique fast_two_add ou fast_two_sum

2024-09-23 12:11 UTC, jtlap commented on include/eve/module/core/regular/impl/rec.hpp
> +                               (spy::compiler == spy::gcc_ && spy::compiler >= 13'0_gcc) || spy::compiler == spy::msvc_))
done

2024-09-23 19:25 UTC, jfalcou requested changes

2024-09-23 19:25 UTC, jfalcou commented on include/eve/module/core/detail/roundings.hpp
> +  bool constexpr enable_roundings = (spy::compiler == spy::clang_ && spy::architecture == spy::amd64_) || spy::compiler == spy::msvc_;
this needs to be inline

2024-09-23 19:25 UTC, jfalcou commented on include/eve/module/core/regular/three_fma.hpp
> +//!   triple  of an fma value f and two errors e1 and e2 such that \f$ax+y = f+r_1+r_2/f$
Everywhere in this documentation, replace triple by triplet

2024-09-24 04:21 UTC, jfalcou approved these changes

2024-09-24 04:22 UTC, merged