Widen (no more narrowing)
jfalcou/eve pull request #1994
Opened 2024-10-07 14:12 UTC by jtlap

2024-10-10 17:14 UTC, jfalcou requested changes
+ remove iostream
+add simd_cast ncludes wherever necessary

2024-10-11 16:10 UTC, jfalcou requested changes

2024-10-11 16:10 UTC, jfalcou commented on include/eve/module/core/regular/impl/simd/arm/neon/add.hpp
> +//     else if constexpr( match(c, category::integer_) && sizeof(T) <= 4 )
Remove and push as NO CI

2024-10-11 16:19 UTC, jtlap commented on include/eve/module/core/regular/impl/simd/arm/neon/add.hpp
> +//     else if constexpr( match(c, category::integer_) && sizeof(T) <= 4 )
ok

2024-10-11 16:38 UTC, jfalcou approved these changes

2024-10-11 16:38 UTC, merged