Issue 344: extending eve - first_true
jfalcou/eve pull request #345
Opened 2020-09-26 17:33 UTC by DenisYaroshevskiy

Example on how one can write custom functions for EVE: in this case first true.

Here is my gist with code:
https://gist.github.com/DenisYaroshevskiy/9b2254ebbdb850bda0f8508ea25fa290

The testing is bad but the functionality mostly copy-pasted from my normal implementation.
I don't know your testing framework unfortunately and I can't build your tests, I would prefer if somebody cleaned that up after me if possible. Or let me know what you need.

2020-10-02 09:01 UTC, jfalcou requested changes
The premises are good. Now:
 - this need rebase to get the new doc structure for crumbs (and add this to the Developer's Corner menu)
 - I think it needs to be split at the ignore part.
 - Other smalls correctiosn as per the reviews

Good job :)

2020-10-03 15:20 UTC, DenisYaroshevskiy commented on docs/tutorial/extending_first_true.html
> +2 - since you need a solution now and not someday (or if EVE's maintainers refuse for some reason)
Removed everything about 'refuse'

2020-10-03 15:20 UTC, DenisYaroshevskiy commented on docs/tutorial/extending_first_true.html
> +At the time of writing EVE doesn't expose `first_true` function. Let's say that we need it to implement
Didn't add the footnote since it doesn't. Done.

2020-10-03 15:21 UTC, DenisYaroshevskiy commented on docs/tutorial/extending_first_true.html
> +  if constexpr (std::same_as<ABI, eve::avx_> && eve::current_api == eve::avx) {
Done. Doing `else` after return and nesting `if` goes against a lot of things I believe in but fine :).

2020-10-03 15:21 UTC, DenisYaroshevskiy commented on docs/tutorial/extending_first_true.html
> +*TODO: what happens when you try to compare x86 and arm for example*.
Wrote the doc as if that's the case already.

2020-10-03 15:22 UTC, DenisYaroshevskiy commented on docs/tutorial/extending_first_true.html
> +concept natural_wide_sse =
We figured this out on slack. Updated.

2020-10-03 15:22 UTC, DenisYaroshevskiy commented on docs/tutorial/extending_first_true.html
> +Supporting eve::ignore
Removed.

2020-10-06 06:40 UTC, jfalcou approved these changes

2020-10-06 06:41 UTC, merged