Elliptic
jfalcou/eve pull request #383
Opened 2020-10-30 14:54 UTC by jtlap

trois fonctions elliptiques am et 2 carlson

2020-11-11 16:31 UTC, jfalcou requested changes

2020-11-11 16:31 UTC, jfalcou commented on include/eve/module/elliptic/function/generic/jacobi_elliptic.hpp
> +//      std::cout << "phi " << phi << std::endl;
Clean up

2020-11-11 16:31 UTC, jfalcou commented on include/eve/module/elliptic/function/generic/jacobi_elliptic.hpp
> +//       std::cout << "sn " << sn << std::endl;
Clean up

2020-11-14 17:30 UTC, jtlap commented on include/eve/module/elliptic/function/generic/jacobi_elliptic.hpp
> +//      std::cout << "phi " << phi << std::endl;
done

2020-11-15 17:28 UTC, jfalcou approved these changes

2020-11-15 17:28 UTC, merged