diff replace derivative in docs
jfalcou/eve pull request #471
Opened 2021-01-21 19:15 UTC by jtlap

only html docs are modified here

2021-01-21 21:19 UTC, jfalcou commented on docs/reference/functions/arithmetic.html
> +:   computes the derivativeerence between 1 and its parameter without lose of precision ($1 - x$)
this diff->derivative looks bad

2021-01-21 21:19 UTC, jfalcou commented on docs/reference/functions/arithmetic/average.html
> +However, problems can arise if the derivativeerence of two parameters
Same error

2021-01-21 21:19 UTC, jfalcou commented on docs/reference/functions/operators/div.html
> +Return the derivativeerence of `x` and `y`.
Again

2021-01-21 21:19 UTC, jfalcou commented on docs/reference/functions/operators/sub.html
> +Return the derivativeerence of `x` and `y`.
Same here

2021-01-21 21:20 UTC, jfalcou commented on docs/reference/functions/operators/sub.html
> + a mere [logical value](../../concepts.html#value) these expressions compute the derivativeerence (resp the saturated
Again

2021-01-21 21:20 UTC, jfalcou commented on docs/tutorial/masking.html
> + - the value to use whenever an element of said condition evaluates to `false`, here the derivativeerence of `a` and `b`
Again again

2021-01-21 21:20 UTC, jfalcou commented on docs/tutorial/masking.html
> +Let's write a function that computes the derivativeerences between two vectors in multiple scenarios: not
and again :)

2021-01-21 21:20 UTC, jfalcou requested changes
you have been a bit too strong with your searcg//repalce

2021-01-21 23:57 UTC, jtlap commented on docs/reference/functions/arithmetic.html
> +:   computes the derivativeerence between 1 and its parameter without lose of precision ($1 - x$)
done

2021-01-21 23:57 UTC, jtlap commented on docs/reference/functions/arithmetic/average.html
> +However, problems can arise if the derivativeerence of two parameters
done

2021-01-21 23:57 UTC, jtlap commented on docs/reference/functions/operators/div.html
> +Return the derivativeerence of `x` and `y`.
done

2021-01-21 23:57 UTC, jtlap commented on docs/reference/functions/operators/sub.html
> +Return the derivativeerence of `x` and `y`.
done

2021-01-21 23:58 UTC, jtlap commented on docs/reference/functions/operators/sub.html
> + a mere [logical value](../../concepts.html#value) these expressions compute the derivativeerence (resp the saturated
done

2021-01-22 09:58 UTC, jfalcou approved these changes

2021-01-22 09:58 UTC, merged