Cleaning operators
jfalcou/eve pull request #483
Opened 2021-01-24 08:20 UTC by jtlap

cleaning as much as possible

2021-01-24 18:50 UTC, jfalcou requested changes

2021-01-24 18:50 UTC, jfalcou commented on test/doc/core/is_equal.cpp
> +            << "-> is_equal(pf ==  qf) = " << eve::is_equal(pf, qf) << '\n';
why this change ?

2021-01-24 20:16 UTC, jtlap commented on test/doc/core/is_equal.cpp
> +            << "-> is_equal(pf ==  qf) = " << eve::is_equal(pf, qf) << '\n';
an error

2021-01-25 08:46 UTC, jfalcou approved these changes

2021-01-25 08:46 UTC, merged