Cpp polish 8
jfalcou/eve pull request #673
Opened 2021-05-02 10:14 UTC by jtlap

2021-05-02 13:20 UTC, jfalcou requested changes

2021-05-02 13:20 UTC, jfalcou commented on test/unit/module/real/core/is_not_equal.cpp
> +  using eve::as;
duplicate line

2021-05-02 13:20 UTC, jfalcou commented on test/unit/module/real/core/is_not_flint.cpp
> +auto mf2 = []<typename T>(eve::as_<T> const & tgt)
blank line needed here, not at line 43 ;)

2021-05-02 13:20 UTC, jfalcou commented on test/unit/module/real/core/is_not_greater.cpp
> +  using eve::as;
duplicate

2021-05-02 13:20 UTC, jfalcou commented on test/unit/module/real/core/is_not_greater_equal.cpp
> +#include <cmath>
why cmath ?

2021-05-02 13:20 UTC, jfalcou commented on test/unit/module/real/core/is_not_greater_equal.cpp
> +    using eve::as;
duplicate

2021-05-02 13:20 UTC, jfalcou commented on test/unit/module/real/core/is_not_less.cpp
> +#include <cmath>
why cmath ?

2021-05-02 13:20 UTC, jfalcou commented on test/unit/module/real/core/is_not_less.cpp
> +    using eve::as;
duplicate

2021-05-02 13:20 UTC, jfalcou commented on test/unit/module/real/core/is_not_less_equal.cpp
> +#include <cmath>
why cmath ? 
copy paste much ?

2021-05-02 13:20 UTC, jfalcou commented on test/unit/module/real/core/is_not_less_equal.cpp
> +  using eve::as;
duplicate

2021-05-02 13:20 UTC, jfalcou commented on test/unit/module/real/core/is_not_real.cpp
> +#include <cmath>
why cmath

2021-05-02 13:20 UTC, jfalcou commented on test/unit/module/real/core/is_pow2.cpp
> +#include <bit>
why bit ?

2021-05-02 13:20 UTC, jfalcou commented on test/unit/module/real/core/is_unordered.cpp
> +#include <cmath>
why cmath ?

2021-05-02 16:27 UTC, jtlap commented on test/unit/module/real/core/is_not_greater_equal.cpp
> +#include <cmath>
all changes done

2021-05-03 06:29 UTC, jtlap commented
j'ai répondu à tes demandes

2021-05-03 08:49 UTC, jfalcou approved these changes

2021-05-03 08:49 UTC, merged