Avx512cmp
jfalcou/eve pull request #839
Opened 2021-08-03 09:24 UTC by jtlap

masked compares

2021-08-03 12:54 UTC, DenisYaroshevskiy reviewed
I'm not against this but I have to ask why.
What would be the use-case.

2021-08-03 14:41 UTC, jtlap commented
frankly the use case is not clear but avx512 has the intrinsics that do the masking with the same lattency as the mere predicate,
so I braugth the interface to eve as we have this for many other function objects.

2021-08-03 14:42 UTC, jtlap commented
I have forgotten to add the doc, I'm on it.

2021-08-03 20:02 UTC, jfalcou requested changes

2021-08-03 20:02 UTC, jfalcou commented on include/eve/function/is_less.hpp
> +#include <eve/constant/false.hpp>
why those includes ?

2021-08-04 09:52 UTC, jtlap commented on include/eve/function/is_less.hpp
> +#include <eve/constant/false.hpp>
suppressed

2021-08-04 15:11 UTC, jtlap commented on include/eve/detail/function/conditional.hpp
> +  EVE_FORCEINLINE auto lalternative(C const& c, as<Target> const&)
done

2021-08-05 16:10 UTC, jfalcou approved these changes

2021-08-05 16:11 UTC, merged