Docv2/misc
jfalcou/eve pull request #849
Opened 2021-08-15 14:36 UTC by jtlap

2021-08-15 18:03 UTC, jfalcou requested changes

2021-08-15 18:03 UTC, jfalcou commented on include/eve/function/fuzzy.hpp
> +  //================================================================================================
Split over each object

2021-08-15 21:20 UTC, jtlap commented on include/eve/concept/value.hpp
> +  //!
done

2021-08-15 21:20 UTC, jtlap commented on include/eve/detail/function/broadcast.hpp
> +  //! `x`:  An instance of an \ref simd_value
done

2021-08-15 21:21 UTC, jtlap commented on include/eve/detail/function/broadcast.hpp
> +  //! If `x` is an instance of a \ref simd_value `T`, the call is equivalent to `T{x.get(I)}`.
done

2021-08-15 21:21 UTC, jtlap commented on include/eve/function/acos.hpp
> +  //!`x`:   [floating real value](@ref eve::value).
done

2021-08-15 21:21 UTC, jtlap commented on include/eve/memory/is_aligned.hpp
> +  //! @tparam  Lanes Alignment constraint to verify expressed as a SIMD register number of lanes.
restored

2021-08-15 21:21 UTC, jtlap commented on include/eve/function/logical_and.hpp
> +  //!if `x` or  `y` is an  [simd value](@ref eve::value) and does not shortcut.
done

2021-08-15 21:21 UTC, jtlap commented on include/eve/function/bit_shl.hpp
> +  //!the call `bit_shl(x, n)` is equivalent to `x << n` if `x`  is an  \link eve::simd_value simd value\endlink.
replaced

2021-08-15 21:22 UTC, jtlap commented on include/eve/function/cos.hpp
> +  //!  As all direct trigonometric functions, `cos` supports the
done

2021-08-15 21:22 UTC, jtlap commented on include/eve/function/derivative.hpp
> +  //!  diff can be declined in
done

2021-08-15 21:22 UTC, jtlap commented on include/eve/function/fuzzy.hpp
> +  //================================================================================================
done

2021-08-16 13:30 UTC, jfalcou approved these changes

2021-08-16 13:31 UTC, merged