Avx512/rol ror
jfalcou/eve pull request #931
Opened 2021-09-10 07:59 UTC by jtlap

2021-09-10 12:35 UTC, jfalcou requested changes

2021-09-10 12:35 UTC, jfalcou commented on include/eve/function/rotl.hpp
> +                                             << -l
why the change here ?

2021-09-10 12:35 UTC, jfalcou commented on include/eve/function/rotr.hpp
> +                                             << -l
Same here

2021-09-10 12:35 UTC, jfalcou commented on include/eve/module/real/core/function/regular/generic/rotl.hpp
> +    //   std::cout << "icotte" << std::endl;
remove don"t comment

2021-09-10 12:35 UTC, jfalcou commented on include/eve/module/real/core/function/regular/generic/rotl.hpp
> +  [[nodiscard]] EVE_FORCEINLINE auto rotl_(EVE_SUPPORTS(cpu_), T a0, U n) noexcept
why the random [[nodiscard]] ?

2021-09-10 12:35 UTC, jfalcou commented on test/unit/module/real/core/rotl.cpp
> +        , eve::test::simd::uints_16//unsigned_integers
why the change ?

2021-09-10 12:35 UTC, jfalcou commented on test/unit/module/real/core/rotl.cpp
> +  std::cout << "a1 " << a1 << std::endl;
remove outputs if not needed

2021-09-10 18:11 UTC, jtlap commented on include/eve/function/rotl.hpp
> +                                             << -l
seemed clearer

2021-09-10 18:14 UTC, jtlap commented on include/eve/module/real/core/function/regular/generic/rotl.hpp
> +    //   std::cout << "icotte" << std::endl;
done

2021-09-10 18:15 UTC, jtlap commented on include/eve/module/real/core/function/regular/generic/rotl.hpp
> +  [[nodiscard]] EVE_FORCEINLINE auto rotl_(EVE_SUPPORTS(cpu_), T a0, U n) noexcept
don't know but not incorrect anyway

2021-09-10 18:20 UTC, jtlap commented on test/unit/module/real/core/rotl.cpp
> +  std::cout << "a1 " << a1 << std::endl;
done

2021-09-10 18:20 UTC, jtlap commented on test/unit/module/real/core/rotl.cpp
> +        , eve::test::simd::uints_16//unsigned_integers
erroneous

2021-09-10 18:25 UTC, jtlap commented on include/eve/module/real/core/function/regular/generic/rotl.hpp
> +  [[nodiscard]] EVE_FORCEINLINE auto rotl_(EVE_SUPPORTS(cpu_), T a0, U n) noexcept
removed

2021-09-11 06:50 UTC, jfalcou approved these changes

2021-09-11 06:51 UTC, merged