powm1
jfalcou/eve pull request #986
Opened 2021-09-28 07:46 UTC by jtlap

just an ulp change

2021-09-28 18:54 UTC, jfalcou requested changes

2021-09-28 18:54 UTC, jfalcou commented on test/unit/module/real/math/powm1.cpp
> +        , eve::test::simd::ieee_doubles
WHy the change ?

2021-09-28 18:54 UTC, jfalcou commented on test/unit/module/real/math/powm1.cpp
> +//  TTS_ULP_EQUAL(eve::diff_1st(eve::powm1)(a0, a1), eve::pow(a0, eve::dec(a1))*a1, 2);
Delete don't comment

2021-09-28 19:01 UTC, jtlap commented on test/unit/module/real/math/powm1.cpp
> +//  TTS_ULP_EQUAL(eve::diff_1st(eve::powm1)(a0, a1), eve::pow(a0, eve::dec(a1))*a1, 2);
removed

2021-09-28 19:01 UTC, jtlap commented on test/unit/module/real/math/powm1.cpp
> +        , eve::test::simd::ieee_doubles
removed

2021-09-29 07:36 UTC, jfalcou approved these changes

2021-09-29 07:36 UTC, merged